[autoridades]
1 = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA35ReZptJSR2U4cX+qfZH
JtauDHkVivtNAnBdqr0461UYs1CFYR1VzwNIgXIUHnU77zKfVjcAiAXwxBGkjNNi
TA9T/Wszr0R4KYz9KfxPOyj4mnJ53bnXQOmxN1mqQ4KL8ld20jjk5zAH1wzGwUf4
GIY8fk9DrILe6uZJHJlw+z8QFYdir4X8f4rChqWnziRBIq49/YrTzL2ER4OTBhjT
FiSjZXiEJeI+IUQ+n0vDiAcb41HkzMA01eM6dbjgn3NZpW2uzj0J/z4R/xrSg3OO
RwWN3R94xXvvpqm7srgQBKPEzdJ8WRu2G5OxvXOQwUxOkYTB8rzHb7C+266BMqbH
YwIDAQAB
-----END PUBLIC KEY-----
"""